// Generates supabase/seed.sql from lib/content/seed.ts (single source of truth).
// Usage: node scripts/generate-seed.mjs   (Node 23.6+ strips TS types natively)
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import * as seed from "../lib/content/seed.ts";

const uuid = (name) => {
  const h = createHash("md5").update(`marketing-house:${name}`).digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};
const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (a) => `array[${a.map(q).join(",")}]::text[]`;
const rows = (table, cols, values) =>
  `insert into public.${table} (${cols.join(", ")}) values\n${values.map((v) => `  (${v.join(", ")})`).join(",\n")}\non conflict do nothing;\n`;

const out = [];
out.push("-- =====================================================================");
out.push("-- Marketing House — seed data (GENERATED by scripts/generate-seed.mjs)");
out.push("-- Projects, testimonials, clients and team are PLACEHOLDERS (is_placeholder = true).");
out.push("-- Run after schema.sql.");
out.push("-- =====================================================================\n");

out.push(rows(
  "services",
  ["id", "slug", "icon", "hue", "title_ar", "title_en", "short_ar", "short_en", "description_ar", "description_en", "tags", "deliverables", "process_steps", "faqs", "sort_order"],
  seed.seedServices.map((s, i) => [
    q(uuid(s.id)), q(s.slug), q(s.icon), s.hue, q(s.title.ar), q(s.title.en), q(s.short.ar), q(s.short.en), q(s.description.ar), q(s.description.en),
    j(s.tags),
    j(s.deliverables.map((d) => ({ title_ar: d.title.ar, title_en: d.title.en, text_ar: d.text.ar, text_en: d.text.en }))),
    j(s.process.map((d) => ({ title_ar: d.title.ar, title_en: d.title.en, text_ar: d.text.ar, text_en: d.text.en }))),
    j(s.faqs.map((f) => ({ q_ar: f.q.ar, q_en: f.q.en, a_ar: f.a.ar, a_en: f.a.en }))),
    i,
  ]),
));

out.push(rows(
  "project_categories",
  ["id", "slug", "name_ar", "name_en", "sort_order"],
  seed.seedCategories.map((c, i) => [q(uuid(c.id)), q(c.slug), q(c.name.ar), q(c.name.en), i]),
));

const catId = (slug) => uuid(seed.seedCategories.find((c) => c.slug === slug).id);
out.push(rows(
  "projects",
  ["id", "slug", "title_ar", "title_en", "client_ar", "client_en", "category_id", "year", "service_slugs", "summary_ar", "summary_en", "challenge_ar", "challenge_en", "solution_ar", "solution_en", "results", "hue", "is_featured", "is_placeholder", "sort_order"],
  seed.seedProjects.map((p, i) => [
    q(uuid(p.id)), q(p.slug), q(p.title.ar), q(p.title.en), q(p.client.ar), q(p.client.en), q(catId(p.categorySlug)), p.year, arr(p.serviceSlugs),
    q(p.summary.ar), q(p.summary.en), q(p.challenge.ar), q(p.challenge.en), q(p.solution.ar), q(p.solution.en),
    j(p.results.map((r) => ({ value: r.value, suffix: r.suffix, label_ar: r.label.ar, label_en: r.label.en }))),
    p.hue, p.featured, p.isPlaceholder, i,
  ]),
));

out.push(rows(
  "testimonials",
  ["id", "name_ar", "name_en", "role_ar", "role_en", "company_ar", "company_en", "quote_ar", "quote_en", "rating", "is_placeholder", "sort_order"],
  seed.seedTestimonials.map((t, i) => [q(uuid(t.id)), q(t.name.ar), q(t.name.en), q(t.role.ar), q(t.role.en), q(t.company.ar), q(t.company.en), q(t.quote.ar), q(t.quote.en), t.rating, t.isPlaceholder, i]),
));

out.push(rows(
  "clients",
  ["id", "name", "is_placeholder", "sort_order"],
  seed.seedClients.map((c, i) => [q(uuid(c.id)), q(c.name), c.isPlaceholder, i]),
));

out.push(rows(
  "team_members",
  ["id", "name_ar", "name_en", "role_ar", "role_en", "socials", "is_placeholder", "sort_order"],
  seed.seedTeam.map((m, i) => [q(uuid(m.id)), q(m.name.ar), q(m.name.en), q(m.role.ar), q(m.role.en), j(m.socials), m.isPlaceholder, i]),
));

out.push(rows(
  "branches",
  ["id", "key", "name_ar", "name_en", "city_ar", "city_en", "address_ar", "address_en", "phone", "whatsapp", "map_embed_url", "map_link", "working_hours_ar", "working_hours_en", "map_x", "map_y", "is_main", "sort_order"],
  seed.seedBranches.map((b, i) => [
    q(uuid(b.id)), q(b.key), q(b.name.ar), q(b.name.en), q(b.city.ar), q(b.city.en), q(b.address.ar), q(b.address.en), q(b.phone), q(b.whatsapp),
    q(b.mapEmbedUrl), q(b.mapLink), q(b.workingHours.ar), q(b.workingHours.en), b.mapX, b.mapY, b.isMain, i,
  ]),
));

const s = seed.seedSettings;
out.push(rows(
  "site_settings",
  ["id", "phone", "whatsapp", "email", "facebook", "instagram", "linkedin", "commercial_reg_no", "tax_card_no", "stat_projects", "stat_clients", "stat_years", "stat_campaigns", "seo_title_ar", "seo_title_en", "seo_description_ar", "seo_description_en"],
  [[1, q(s.phone), q(s.whatsapp), q(s.email), q(s.facebook), q(s.instagram), q(s.linkedin), q(s.commercialRegNo), q(s.taxCardNo), s.stats.projects, s.stats.clients, s.stats.years, s.stats.campaigns, q(s.seoTitle.ar), q(s.seoTitle.en), q(s.seoDescription.ar), q(s.seoDescription.en)]],
));

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n"));
console.log("supabase/seed.sql written");
